### ISSUE TITLE
IconButton Badge

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-ui#10]
**Is your feature request related to a problem? Please describe.**

Please describe the problem you are trying to solve.
Badges in Buttons

**Describe the solution you'd like**

Please describe the desired behavior.
IconButton Badge
![image](https://user-images.githubusercontent.com/30869823/106648959-3f347d80-6591-11eb-9616-54e411787ae3.png)

**Comment by anubra266** [comment]
@MichaelGrigoryan25 You can name your pull request as 
`Closes #10` 
So merging it closes this issue automatically.

**Comment by MichaelGrigoryan25** [comment]
Will do 👍

**Comment by anubra266** [comment]
@MichaelGrigoryan25 any update on this?

**Comment by MichaelGrigoryan25** [comment]
> @MichaelGrigoryan25 any update on this?

https://github.com/anubra266/choc-ui/pull/17#issuecomment-774152414
