### ISSUE TITLE
Feature Request - Footer

### ISSUE THREAD

**Issue by AbbyB97** [anubra266/choc-ui#143]
Hey @anubra266 , This looks like an awesome initiative I think the collection deserves an attractive footer I am thinking of adding something like this let me know if I should work on this I ll add some extra changes as well along with light and dark theming
![footer](https://user-images.githubusercontent.com/19248801/172680122-ad4998a0-0f98-4b10-87b9-ac30ab48c308.jpg)

**Comment by anubra266** [comment]
Hi @AbbyB97 Feel free to work on it. But I'll soon revamp the whole site. The new one is [here](https://github.com/anubra266/choc-ui) So maybe add it there.

**Comment by AbbyB97** [comment]
@anubra266  I ll just add it there so thats easy for you thank you :D

**Comment by AbbyB97** [comment]
Closing this issue as it was resolved with one of my PRs and new feature was added .
