### ISSUE TITLE
Form tccst radio and checkboxes fix for light mode and small font changes in the company footer

### ISSUE THREAD

**Issue by AbbyB97** [anubra266/choc-ui#149]
Hey @anubra266  I think we should fix the tccst form the radio buttons and checkboxes are not at all visible. I have made the changes in local I ll link the pr here itself. checkout the image
![Screenshot from 2022-06-14 16-59-18](https://user-images.githubusercontent.com/19248801/173567162-575aed6c-de55-4235-ab88-f4fd2768125b.png)

**Comment by AbbyB97** [comment]
Here is the PR for the changes mentioned.
https://github.com/anubra266/choc-ui/pull/150

**Comment by anubra266** [comment]
@AbbyB97 The issues in the form component are due to #148.

**Comment by AbbyB97** [comment]
@anubra266 Oh alright
