### ISSUE TITLE
Pl fix Push Alert Notification in the site : https://choc-ui.tech/docs/installation#deny 

### ISSUE THREAD

**Issue by veerjainATgmail** [anubra266/choc-ui#26]
![image](https://user-images.githubusercontent.com/13132206/111106090-6875ff80-857a-11eb-86b8-4c4b91f6b977.png)

Hi... Just not able to go through the documentation due to this persistant alert. Kindly fix

**Comment by anubra266** [comment]
Thanks for bringing attention to this. Please confirm that it's been fixed.

**Comment by anubra266** [comment]
Sorry, the fix was not elevated to production. Now fixed.
