### ISSUE TITLE
Strange behavior on the carousels component

### ISSUE THREAD

**Issue by LunacTec** [anubra266/choc-ui#27]
In order to see this 'bug', go to the Choc UI docs, to the carousel showcase. Then click the left arrow to see what happends (you go from the first element on the carousel to the last one). If you click again on the same arrow, it will go back to the first element on the carrousel instead of the penultimate one.

**Comment by anubra266** [comment]
It has been replaced with a new one, the previous uses a method not compatible with all browsers.
[Check it out](https://choc-ui.tech/docs/elements/carousels)
