### ISSUE TITLE
Can't see code for Forms snippet in docs

### ISSUE THREAD

**Issue by lowercase00** [anubra266/choc-ui#41]
I was looking at the form components, but when I click "view code" button, it doesn't show anything.

**Comment by anubra266** [comment]
Hi! sorry for the late answer. The code snippet opens. The problem is that it opens at the bottom of the preview, so you have to scroll down to see it. I'm thinking a drawer might be a better fit for the code snippet. What do you think?

**Comment by buzzeh** [comment]
> Hi! sorry for the late answer. The code snippet opens. The problem is that it opens at the bottom of the preview, so you have to scroll down to see it. I'm thinking a drawer might be a better fit for the code snippet. What do you think?

Is there a particular reason why all 3 forms are in a single section instead of individual ones? I feel like that could also clear the confusion

**Comment by anubra266** [comment]
@buzzeh That particular example is imitating a typical settings page that usually contains all the sections
