### ISSUE TITLE
Feature Request: I want a Button that can switch the viewer size between PC, tablet, and smartphone.

### ISSUE THREAD

**Issue by mochi-sann** [anubra266/choc-ui#61]
I'd like to see a button that can switch the viewer size when the button is pressed, like https://chakra-templates.dev/page-sections/hero
<img width="196" alt="screenshot 2021-11-29 12 10 06" src="https://user-images.githubusercontent.com/44772513/143803032-cfe0ccf9-89de-4420-bfe0-a5a190e20024.png">

https://user-images.githubusercontent.com/44772513/143803142-3c7f6642-81ad-4854-9c04-70a1147a6d82.mov

**Comment by mochi-sann** [comment]
If you'd like to add it, I can implement it myself.

**Comment by anubra266** [comment]
Feel free to work on this @mochi-sann
