### ISSUE TITLE
Warning: React has detected a change in the order of Hooks called by PaginationComp. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

### ISSUE THREAD

**Issue by yepes** [anubra266/choc-ui#67]
Hi

I'm using the pagination component with react table, the implementation looks something like this:

```jsx
<Pagination
  defaultCurrent={initialPageIndex + 1}
  total={totalResults}
  paginationProps={{ display: "flex" }}
  baseStyles={{ bg: "white" }}
  hoverStyles={{ bg: "gray.50" }}
  activeStyles={{ bg: "gray.100" }}
  pageNeighbours={3}
  showTotal={(total) => `Mostrando ${page.length} de ${total} resultados`}
  onChange={(page) => {
    gotoPage(page - 1)
  }}
/>
```

I'm getting the following warning when I refresh the page:

```Warning: React has detected a change in the order of Hooks called by PaginationComp. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks```

**Comment by anubra266** [comment]
Hi @yepes, could you create a codesandbox reproduction. Thanks

**Comment by yepes** [comment]
> Hi @yepes, could you create a codesandbox reproduction. Thanks

My bad, it was on my end. Closing this.

**Comment by anubra266** [comment]
Ok...thanks @yepes

**Comment by youngrove** [comment]
what was the issues?

**Comment by valimail-scott** [comment]
> > Hi @yepes, could you create a codesandbox reproduction. Thanks
> 
> My bad, it was on my end. Closing this.

@yepes what did this end up being in your case? I have the same issue.

**Comment by yepes** [comment]
> > > Hi @yepes, could you create a codesandbox reproduction. Thanks
> > 
> > 
> > My bad, it was on my end. Closing this.
> 
> @yepes what did this end up being in your case? I have the same issue.

Hey @valimail-scott, i'm sorry, i can't remember, it was almost three years ago.
