### ISSUE TITLE
Expired choc-ui.tech - (It was moved to https://choc-ui.com)

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-ui#70]

**Comment by iErcann** [comment]
https://chakra-ui.com/showcase still shows .tech domain

**Comment by anubra266** [comment]
Thanks @iErcann . Didn't even know that showcase site existed. 😂

**Comment by anubra266** [comment]
@iErcann Someone opened a PR here: https://github.com/chakra-ui/awesome-chakra-ui/pull/24
